spring:
  application:
    name : FileManager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/filetest
    username: postgres
    password: 10174
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      password:

app:
  upload:
    base-path: ./uploads/temp
    final-path: ./uploads/fin
#    base-path: "/var/myapp/uploads/temp" for production

  redis:
    progress-key-prefix: "progress : "
    chunk-key-prefix: "Chunk : "